Ansteorra/KMP

- app/plugins/Awards/src/Controller/RecommendationsController.php
> Add "submitted by" to export CSV

- app/plugins/Activities/src/Controller/ReportsController.php
- app/plugins/Activities/templates/Reports/authorizations.php
> *Add branch filter for authorizations reports

- app/plugins/Activities/src/Controller/AuthorizationApprovalsController.php
- app/plugins/Activities/templates/AuthorizationApprovals/index.php
- app/src/Controller/MembersController.php
making the auth queue sortable and searchable by name and email address.  also removing disabled users from autocomplete searches for members.
> fix issue #175 and #179

- app/assets/css/app.css
- app/templates/Members/add.php
- app/templates/Members/register.php
- app/webroot/css/app.css
- app/webroot/mix-manifest.json
just adding an extra css rule to labels and hand adding the new rule to the date field on adding and registering users..
> added ui element in CSS to make required fields visible.

- app/config/Migrations/20240921145957_AddTitlePronounsPronunciationToMembers.php
- app/src/Controller/MembersController.php
- app/src/Model/Entity/Member.php
- app/templates/Members/add.php
- app/templates/Members/register.php
- app/templates/element/members/editModal.php
- app/templates/element/members/memberDetails.php
*Add new fields to MemberDetail elements
*Add new fields to register/add
*Add title to authorization cards view
> *Add Title/Pronouns/Pronunciation to model

- app/src/Controller/MembersController.php
- app/src/View/Helper/KmpHelper.php
There were edge cases where a child who had their parent verified but not their membership, the membership card would get deleted.
> Fix small issue with cards deleting before verification.

- app/assets/css/dashboard.css
- app/templates/element/copyrightFooter.php
- app/templates/layout/TwitterBootstrap/dashboard.php
- app/templates/layout/TwitterBootstrap/view_record.php
- app/webroot/css/app.css
- app/webroot/css/dashboard.css
- app/webroot/mix-manifest.json
Added updates to header and footer so that people could create links at the top and bottom of the portal pages.
> implement basic functionality for issue #200 and some other CSS tweaks

- app/src/Controller/MembersController.php
> Member search handles Þ in name branch and email

- app/plugins/Activities/src/Controller/AuthorizationApprovalsController.php
> Authorizations Queues handles Þ

- app/config/routes.php
- app/src/Controller/SessionsController.php
- app/templates/layout/TwitterBootstrap/dashboard.php
- app/templates/layout/TwitterBootstrap/view_record.php
- app/webroot/js/sessionExtender.js
> added Alert that triggers ajax request to extend session if clicked 

- app/plugins/Awards/templates/Recommendations/table.php
> Resolves #251 removed member link on recommendation list if unauthorized to view 

- app/src/Model/Entity/Member.php
had a >=17 in the age up check that should have been just an >
> age up routine was checking for 17 and older should have been older than 17

- app/plugins/Awards/src/Controller/RecommendationsController.php
> SET BOM to true for csvview plugin on export

- app/plugins/Awards/Assets/js/controllers/rec-bulk-edit-controller.js
- app/plugins/Awards/Assets/js/controllers/rec-quick-edit-controller.js
- app/plugins/Awards/Assets/js/controllers/rec-table-controller.js
- app/plugins/Awards/src/Controller/RecommendationsController.php
- app/plugins/Awards/templates/Recommendations/bulk.php
- app/plugins/Awards/templates/Recommendations/table.php
- app/plugins/Awards/templates/Recommendations/turbo_bulk_edit_form.php
- app/plugins/Awards/templates/element/recommendationsBulkEditModal.php
> Multi select reccomendations

- app/src/Model/Table/AppSettingsTable.php
last PR of the night going to call it as I have made 3 bone headed mistakes in a row.
> remove little export that I didn't mean to leave in.

- app/plugins/Officers/src/Controller/OfficersController.php
> /officers/officers/api

- app/src/Controller/BranchesController.php
- app/templates/Branches/index.php
> Branches Searchable by name location and parent line groups names

- app/templates/Branches/index.php
Added turbo frame control to view button
> Branch search feature updated

- app/plugins/Officers/src/Services/DefaultOfficerManager.php
> fix call to notify release

- app/src/Controller/WarrantRostersController.php
- app/src/Policy/WarrantPolicy.php
last round of bug fixes before pushing 1.2.1 Email Queueing and Warrant Improvements.
> minor fixes to the permissions

- app/plugins/Officers/src/Controller/OfficersController.php
Added 2 optional query params to officers API
status - shows only officers with that status
endsIn - shows only officers with End dates within X number of days from today
ex
/officers/officers/api?status=current&endsIn=90
/officers/officers/api?status=current
/officers/officers/api?endsIn=45
> added status and endsIn query params

- app/plugins/Awards/src/Controller/RecommendationsController.php
Resolve emergent bug with export not filtering by event
> Exploded url to remove file extension when getting pageConfig in export function

- app/plugins/Activities/templates/cell/MemberAuthorizations/display.php
End users don't see this but its a bug.. so quick fix
> Small fix to remove a warning that renders in debug mode.

- app/src/Services/WarrantManager/DefaultWarrantManager.php
- app/templates/email/text/notify_of_warrant.php
Code fix to handle deactivating Current but older warrants when newer warrants are approved.
> Fix to handle deactivating "older" warrants when a new one is issued.

- .devcontainer/init_env/install_mssql.sh
- app/config/Seeds/InitMembersSeed.php
- app/package-lock.json
- app/plugins/Activities/src/ActivitiesPlugin.php
- app/plugins/Activities/src/Controller/AuthorizationsController.php
- app/plugins/Activities/templates/cell/MemberAuthorizations/display.php
- app/plugins/Awards/src/Controller/RecommendationsController.php
- app/plugins/Awards/templates/Recommendations/table.php
- app/src/KMP/StaticHelpers.php
- app/src/Model/Table/AppSettingsTable.php
- app/templates/Members/index.php
- app/templates/Members/view.php
Back out the GW integrations now that it has been disabled. 
Fix Bug with Bulk Edit of recommendations UI not having security check.. (this is just a UI bug but still worth fixing)
> back out GW integration and fix UI Bulk Edit bug

- app/plugins/Awards/src/AwardsPlugin.php
- app/plugins/Awards/src/Controller/AwardsController.php
- app/plugins/Awards/src/Controller/EventsController.php
- app/plugins/Awards/src/Controller/RecommendationsController.php
- app/plugins/Awards/src/Model/Entity/Recommendation.php
- app/plugins/Awards/src/Model/Table/AwardsTable.php
- app/plugins/Awards/src/Model/Table/EventsTable.php
- app/plugins/Awards/src/Model/Table/RecommendationsTable.php
- app/plugins/Awards/src/Policy/AwardPolicy.php
- app/plugins/Awards/src/Policy/AwardsTablePolicy.php
- app/plugins/Awards/src/Policy/RecommendationPolicy.php
- app/plugins/Awards/src/Policy/RecommendationsTablePolicy.php
- app/plugins/Awards/templates/Awards/view.php
- app/plugins/Awards/templates/Events/view.php
- app/plugins/Awards/templates/Recommendations/view.php
- app/src/KMP/PermissionsLoader.php
- app/src/Model/Entity/Member.php
Enhance permissions management by updating optional permissions, applying authorization scopes in controllers, and improving policy classes for better branch management. This refactor aims to streamline access control and ensure more efficient permission checks.
> Refactor permissions handling in Awards plugin

- app/src/Controller/MemberRolesController.php
This pull request refines the `MemberRolesController` in the `app/src/Controller/MemberRolesController.php` file. The changes include stricter type declarations, adjustments to the authorization logic, and improved error handling for the `deactivate` method.
* Removed the `deactivate` action from the list of authorized model actions in the `initialize` method.
* Added logic in the `deactivate` method to check if the requested `MemberRole` exists. If not, the database transaction is rolled back, and a `NotFoundException` is thrown with a 404 error message.
* Added `declare(strict_types=1)` at the beginning of the file for stricter type checking.
> refactor: fix not being able to deactivate a directly granted role.

- docs/4.1-member-lifecycle.md
This pull request includes a small formatting change in the `docs/4.1-member-lifecycle.md` file. An extra code block delimiter was added after the `classDiagram` section to improve the document's readability.
> Fix mermaid bug in 4.1
